using System;
using System.Collections.Generic;
using Unity.Collections;
using UnityEngine;
using UnityEngine.Experimental.Rendering;
using UnityEngine.Experimental.Rendering.RenderGraphModule;
using UnityEngine.Rendering;

namespace HN.HNRP
{
    /// <summary>
    /// HNRP custom render pipeline implementation.
    /// Uses <see cref="CameraRenderer"/> per camera with a shared <see cref="RenderGraph"/>
    /// instance. Each camera selects its own <see cref="RenderGraphAsset"/> via the
    /// priority chain: <c>pipelineConfigOverride ?? defaultXxxRenderGraph ?? null</c>.
    /// </summary>
    public class HNRenderPipeline : RenderPipeline
    {
        /// <summary>
        /// Gets the pipeline asset that owns this pipeline instance.
        /// Unlike the static <see cref="Asset"/> property (which reads from
        /// <see cref="GraphicsSettings.currentRenderPipeline"/>), this instance
        /// reference is set at construction time and works in EditMode tests.
        /// </summary>
        public static HNRenderPipelineAsset InstanceAsset;

        /// <summary>
        /// Renders realtime reflection probes before all main cameras. Owns the
        /// pooled probe cameras; dispose via <see cref="Dispose(bool)"/>.
        /// </summary>
        private readonly ReflectionProbeRenderer reflectionProbeRenderer;

        private RuntimeReflectionSystem runtimeReflectionSystem;

        /// <summary>
        /// The reflection probe currently being baked via
        /// <see cref="ReflectionProbe.RenderProbe(RenderTexture)"/> (Editor bake/custom flow).
        /// Set by the editor immediately before calling <c>RenderProbe</c> and cleared after,
        /// so the triggered reflection camera render can select the probe's render graph view
        /// instead of the temporary camera's own (default) view index.
        /// </summary>
        public static ReflectionProbe BakingReflectionProbe { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="HNRenderPipeline"/> class.
        /// </summary>
        /// <param name="asset">The pipeline asset providing configuration.</param>
        public HNRenderPipeline(HNRenderPipelineAsset asset)
        {
            InstanceAsset = asset;

            SetSupportedRenderingFeatures();

            reflectionProbeRenderer = new ReflectionProbeRenderer(new ReflectionProbeCameraPool());

            // Register all [Pass]-decorated pass types before building any render graph.
            // In the Editor this uses reflection to scan assemblies; in Player builds it
            // uses the hardcoded table generated by PassRegistryGenerator.
            PassRegistry.RegisterAll();

            GraphicsSettings.lightsUseLinearIntensity = QualitySettings.activeColorSpace == ColorSpace.Linear;
            GraphicsSettings.lightsUseColorTemperature = true;
            GraphicsSettings.defaultRenderingLayerMask = defaultRenderingLayerMask;
            GraphicsSettings.useScriptableRenderPipelineBatching = true;

            try
            {
                Blitter.Initialize(
                    asset.runtimeResources.shaderResources.Blit,
                    asset.runtimeResources.shaderResources.BlitColorAndDepth);
            }
            catch (Exception)
            {
                // Blitter may already be initialized (e.g. by a previous test pipeline).
                // This is safe to ignore.
            }

            RTHandles.SetReferenceSize(Screen.width, Screen.height);

            // RTHandles.Initialize is obsolete and can only be called once before any
            // RTHandle allocation. Guard it with a static flag so repeated pipeline
            // construction (e.g. multiple HNRenderPipeline instances in EditMode tests,
            // or while the Editor's render loop is allocating transient targets) does
            // not trigger the "should only be called once" error. Per-frame sizing is
            // handled by RTHandles.SetReferenceSize inside Render().
            if (!s_RTHandlesInitialized)
            {
                RTHandles.Initialize(Screen.width, Screen.height);
                s_RTHandlesInitialized = true;
            }
        }

        /// <inheritdoc />
        protected override void Render(ScriptableRenderContext context, Camera[] cameras)
        {
            Render(context, new List<Camera>(cameras));
        }

        /// <inheritdoc />
        protected override void Render(ScriptableRenderContext context, List<Camera> cameras)
        {
            BeginContextRendering(context, cameras);

#if UNITY_EDITOR
            if (globalSettings == null || HNRenderPipelineGlobalSettings.Instance == null)
            {
                globalSettings = HNRenderPipelineGlobalSettings.Ensure();
                if (globalSettings == null)
                    return;
                
                RenderGraphTemplates.EnsureAll();
            }
#endif
            
            var cmd = CommandBufferPool.Get("HNRP");
            var parameters = new RenderGraphParameters
            {
                currentFrameIndex = Time.frameCount,
                executionName = "HNRP",
                scriptableRenderContext = context,
                commandBuffer = cmd,
                rendererListCulling = false,
            };

            if (runtimeReflectionSystem == null)
            {
                runtimeReflectionSystem = new RuntimeReflectionSystem();
                ScriptableRuntimeReflectionSystemSettings.system = runtimeReflectionSystem;
            }

            // ── Phase A: cull every camera, collect realtime probes ──
            // Realtime reflection probes render before all main cameras, so every
            // camera is culled first (results cached in CameraContext) and visible
            // realtime probes are collected. CullingResults stay valid for the rest
            // of this Render call and are reused in Phase C.
            var cameraContexts = new List<CameraContext>();
            var selectedGraphs = new Dictionary<Camera, RenderGraphAsset>();
            reflectionProbeRenderer.BeginFrame();

            foreach (Camera camera in cameras)
            {
                // ── Select RenderGraphAsset ──
                RenderGraphAsset renderGraphAsset;

                if (camera.cameraType == CameraType.Preview)
                {
                    string cameraName = camera.name;
                    if (cameraName == HNRenderPipelineUtils.PREVIEW_CAMERA_NAME)
                    {
                        renderGraphAsset = InstanceAsset.gameViewRenderGraphViewBlock.GetRenderGraphObject();
                    }
                    else if (cameraName == HNRenderPipelineUtils.PREVIEW_SCENE_CAMERA_NAME)
                    {
                        renderGraphAsset = InstanceAsset.previewRenderGraphViewBlock.GetRenderGraphObject();
                    }
                    else
                    {
                        if(camera.TryGetComponent<HNRenderpipelinePreviewCameraSettings>(out var previewCameraSettings))
                        {
                            renderGraphAsset = previewCameraSettings.GetPreviewCameraGraphView();
                        }
                        else
                        {
                            renderGraphAsset = InstanceAsset.previewRenderGraphViewBlock.GetRenderGraphObject();
                        }
                    }
                }

                if (camera.cameraType == CameraType.Reflection)
                {
                    // Bake/custom 触发的 reflection 相机（ReflectionProbe.RenderProbe）：
                    // 不经过主相机的 realtime 探针收集，直接按 bake 中 probe 的
                    // render graph view 渲染。临时相机不挂 HNAdditionalCameraData。
                    renderGraphAsset = ReflectionProbeRenderUtils.SelectReflectionRenderGraph(
                        InstanceAsset, BakingReflectionProbe);
                }
                else
                {
                    var cameraData = camera.GetHNRPAdditionalCameraData();
                    renderGraphAsset = SelectPipelineConfig(camera, cameraData);
                }

                if (renderGraphAsset == null)
                    continue;

                // ── Create CameraContext ──
                var cameraContext = new CameraContext(camera, context)
                {
                    Flip = SystemInfo.graphicsUVStartsAtTop
                        && camera.cameraType != CameraType.SceneView
                        && camera.cameraType != CameraType.Preview,
                    RuntimeResources = InstanceAsset.runtimeResources,
                };

                // ── Cull ──
                bool gotParams = camera.TryGetCullingParameters(out ScriptableCullingParameters cullingParams);
                if (gotParams)
                {
                    cameraContext.CullingResults = context.Cull(ref cullingParams);
                    cameraContext.HasCullingResults = true;

                    // Populate visible light array so lighting passes
                    // (e.g. BuildLightDataPass) can consume it.
                    // CameraContext.Dispose releases the array.
                    cameraContext.VisibleLights = new NativeArray<UnityEngine.Rendering.VisibleLight>(
                        cameraContext.CullingResults.visibleLights, Allocator.TempJob);

                    if (camera.cameraType != CameraType.Reflection)
                    {
                        cameraContext.VisibleReflectionProbes =
                            new NativeArray<UnityEngine.Rendering.VisibleReflectionProbe>(
                                cameraContext.CullingResults.visibleReflectionProbes, Allocator.TempJob);

                        // Collect realtime probes visible to this camera.
                        reflectionProbeRenderer.CollectReflectionProbes(cameraContext.VisibleReflectionProbes);
                    }
                }

                cameraContexts.Add(cameraContext);
                selectedGraphs[camera] = renderGraphAsset;
            }

            // ── Phase B: render realtime probes before all main cameras ──
            // Each probe face executes in its own RecordAndExecute block (inside
            // RenderProbes) so the per-face camera matrix is active when its passes run.
            reflectionProbeRenderer.RenderProbes(context, renderGraph, parameters, InstanceAsset);

            // Record all camera passes into the graph; RenderGraphExecution.Dispose()
            // (at the end of this block) compiles and executes the recorded passes.
            using (renderGraph.RecordAndExecute(parameters))
            {
                // ── Phase C: render main cameras using cached culling results ──
                foreach (CameraContext cameraContext in cameraContexts)
                {
                    Camera camera = cameraContext.Camera;
                    if (!selectedGraphs.TryGetValue(camera, out RenderGraphAsset renderGraphAsset) ||
                        renderGraphAsset == null)
                        continue;

                    // ── Per-camera setup ──
                    RTHandles.SetReferenceSize(camera.pixelWidth, camera.pixelHeight);

                    if (camera.targetTexture != null)
                    {
                        camera.targetTexture.IncrementUpdateCount();
                    }

#if UNITY_EDITOR
                    if (camera.cameraType == CameraType.SceneView)
                    {
                        ScriptableRenderContext.EmitWorldGeometryForSceneView(camera);
                    }
#endif

                    SetupCameraProperties(context, camera);

                    var globalConstantBuffer = new GlobalConstantBuffer();
                    GlobalConstantBufferUtility.FillFromCamera(
                        camera,
                        true,
                        ref globalConstantBuffer);
                    ConstantBuffer.PushGlobal(
                        cmd,
                        globalConstantBuffer,
                        GlobalPropertyIDs.ShaderVariablesGlobal);

                    // ── Create CameraRenderer, build from template, render ──
                    var cameraRenderer = new CameraRenderer(cameraContext);
                    cameraRenderer.Build(renderGraphAsset);

                    BeginCameraRendering(context, camera);
                    cameraRenderer.Render(renderGraph, context);
                    EndCameraRendering(context, camera);

                    // cameraContext.Dispose() is deferred until after the
                    // RecordAndExecute block: the render graph compiles and executes
                    // recorded passes at the end of that block, and the BuildLightData
                    // job (which reads VisibleLights) must complete before the native
                    // arrays are released.
                }
            }

            // ── Execute all recorded render graph passes ──
            renderGraph.EndFrame();

#if UNITY_EDITOR
            // HNRP 物体渲染（DrawObjectPass）用 Y 翻转投影矩阵（renderIntoTexture=true），
            // 把全局 unity_MatrixVP 设成翻转矩阵。Unity Editor 内部绘制 SceneView 的
            // grid（xz 网格平面）依赖非翻转的全局 unity_MatrixVP，需在此恢复，否则 grid 颠倒。
            foreach (CameraContext cameraContext in cameraContexts)
            {
                Camera camera = cameraContext.Camera;
                if (camera.cameraType == CameraType.SceneView)
                {
                    cmd.SetViewProjectionMatrices(camera.worldToCameraMatrix, camera.projectionMatrix);
                    break;
                }
            }
#endif

            // ── Cleanup per-camera contexts after execution ──
            foreach (CameraContext cameraContext in cameraContexts)
            {
                cameraContext.Dispose();
            }

            reflectionProbeRenderer.EndFrame();

            // RenderGraph records commands into the command buffer; submit them to the context.
            context.ExecuteCommandBuffer(cmd);
            cmd.Clear();

            context.Submit();

            CommandBufferPool.Release(cmd);

            EndContextRendering(context, cameras);
        }

        /// <summary>
        /// Selects the <see cref="RenderGraphAsset"/> for a camera using the priority chain:
        /// <c>pipelineConfigOverride ?? defaultXxxRenderGraph ?? null</c>.
        /// </summary>
        /// <param name="camera">The camera being rendered.</param>
        /// <param name="cameraData">The camera's additional data component.</param>
        /// <returns>
        /// The selected <see cref="RenderGraphAsset"/>, or <c>null</c> if no render graph
        /// is available (camera will be skipped).
        /// </returns>
        public RenderGraphAsset SelectPipelineConfig(Camera camera, HNAdditionalCameraData cameraData)
        {
            // Step 1: Get the render graph view block for this camera type
            RenderGraphViewBlock viewBlock = GetViewBlockForCameraType(camera.cameraType);
            if (viewBlock == null)
                return null;

            // Step 2: Get the render graph by index from the view block
            int index = cameraData.RenderGraphViewIndex;
            RenderGraphAsset config = viewBlock.GetRenderGraphObject(index);
            if (config != null)
                return config;

            // Step 3: Fall back to the first render graph in the block
            return viewBlock.GetRenderGraphObject();
        }

        /// <summary>
        /// Gets the <see cref="RenderGraphViewBlock"/> from <see cref="HNRenderPipelineAsset"/>
        /// based on the camera type.
        /// </summary>
        /// <param name="cameraType">The camera's type.</param>
        /// <returns>The view block for the given camera type, or <c>null</c>.</returns>
        private RenderGraphViewBlock GetViewBlockForCameraType(CameraType cameraType)
        {
            return cameraType switch
            {
                CameraType.Game => InstanceAsset.gameViewRenderGraphViewBlock,
#if UNITY_EDITOR
                CameraType.SceneView => InstanceAsset.sceneViewRenderGraphViewBlock,
                CameraType.Preview => InstanceAsset.previewRenderGraphViewBlock,
#endif
                CameraType.Reflection => InstanceAsset.reflectionRenderGraphViewBlock,
                _ => null,
            };
        }


        private static void SetSupportedRenderingFeatures()
        {
#if UNITY_EDITOR
            SupportedRenderingFeatures.active = new SupportedRenderingFeatures()
            {
                reflectionProbeModes = SupportedRenderingFeatures.ReflectionProbeModes.Rotation,
                defaultMixedLightingModes = SupportedRenderingFeatures.LightmapMixedBakeModes.IndirectOnly,
                mixedLightingModes = SupportedRenderingFeatures.LightmapMixedBakeModes.IndirectOnly,
                lightmapBakeTypes = LightmapBakeType.Baked | LightmapBakeType.Mixed | LightmapBakeType.Realtime,
                lightmapsModes = LightmapsMode.NonDirectional | LightmapsMode.CombinedDirectional,
                lightProbeProxyVolumes = true,
                motionVectors = true,
                receiveShadows = false,
                reflectionProbes = false,
                rendererPriority = true,
                overridesFog = true,
                overridesOtherLightingSettings = true,
                editableMaterialRenderQueue = false,
                enlighten = true,
                overridesLODBias = true,
                overridesMaximumLODLevel = true,
                overridesShadowmask = true,
                overridesRealtimeReflectionProbes = true,
                autoAmbientProbeBaking = false,
                autoDefaultReflectionProbeBaking = false,
                rendersUIOverlay = true,
                supportsHDR = true
            };
#endif
        }

        /// <summary>
        /// Sets up per-frame camera properties (VP matrix, etc.) on the render context.
        /// </summary>
        /// <param name="context">The scriptable render context.</param>
        /// <param name="camera">The camera to set up.</param>
        private static void SetupCameraProperties(ScriptableRenderContext context, Camera camera)
        {
            var cmd = CommandBufferPool.Get("CameraSetup");
            context.ExecuteCommandBuffer(cmd);
            cmd.Clear();
            CommandBufferPool.Release(cmd);

            context.SetupCameraProperties(camera);
        }

        /// <inheritdoc />
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            Blitter.Cleanup();

            Graphics.SetRenderTarget(null);

            renderGraph.Cleanup();
            renderGraph = null;

            reflectionProbeRenderer.Dispose();

            ConstantBuffer.ReleaseAll();
        }

        /// <summary>
        /// Gets the current pipeline asset. Convenience accessor.
        /// </summary>
        public static HNRenderPipelineAsset Asset
        {
            get => GraphicsSettings.currentRenderPipeline as HNRenderPipelineAsset;
        }

        /// <summary>
        /// The shared <see cref="RenderGraph"/> instance used across all cameras.
        /// All cameras record their passes into this graph inside a
        /// <c>RecordAndExecute</c> block each frame; <see cref="RenderGraph.EndFrame"/>
        /// releases frame resources afterwards.
        /// </summary>
        internal RenderGraph renderGraph = new RenderGraph("HNRP");

        /// <inheritdoc />
        public override RenderPipelineGlobalSettings defaultSettings => globalSettings;

        private HNRenderPipelineGlobalSettings globalSettings;

        /// <summary>
        /// Guards the once-only <see cref="RTHandles.Initialize"/> call. See the
        /// constructor for details.
        /// </summary>
        private static bool s_RTHandlesInitialized;

        internal const int defaultRenderingLayerMask = 0x00000001;
    }
}
